#自定义配置
roncoo: 
  secret: ${random.value}
  number: ${random.int}
  name: www.roncoo.com
  desc: ${roncoo.name} is a domain name
 
#端口
server: 
  port: 8091

mybatis:
    type-aliases-package: com.example.demo.bean
    mapper-locations: classpath:mapper/*.xml
    configuration:
       cache-enabled: true


#spring jsckson
spring: 
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing
    
  #数据源配置
  datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      
  redis:
      host: localhost
      port: 6379
      password: 12345
      timeout: 0
      database: 1
      pool:
        max-active: 8
        max-idle: 50
        min-idle: 10
        max-wait: 10000


    
    